name: glacier_velocity
channels:
  - conda-forge
dependencies:
  - python=3.13
  - geopandas
  - rioxarray
  - boto3
  - pystac-client
  - dask  # for s2 clipping in parallel
  - gdal=3.10.3  # Fixed to 3.10.3 - newer versions trigger warnings, may not be thoroughly tested
  - opencv # pip is called opencv-python
  - tqdm
  - netcdf4
  #- rasterio  # dependency of rioxarray
  #- pystac  # dependency of pystac-client
